my_dbt_project:
  outputs:
    dune_source:
      type: postgres
      host: localhost
      port: 5432
      user: your_username
      password: your_password
      dbname: dune_db
      schema: public
    backend_test_source:
      type: postgres
      host: localhost
      port: 5432
      user: your_username
      password: your_password
      dbname: backend_test
      schema: public
    target:
      type: postgres
      host: localhost
      port: 5432
      user: your_username
      password: your_password
      dbname: data_models
      schema: public
  target: dune_source  # the default target; this can be switched dynamically.