dbt_poc:
  outputs:
    analytics_postgres:
      type: postgres
      host: "{{ env_var('ANALYTICS_URL') }}" 
      port: 5432
      user: "{{ env_var('ANALYTICS_USER') }}"  
      password: "{{ env_var('ANALYTICS_PASSWORD') }}"
      dbname: "{{ env_var('ANALYTICS_DB_NAME') }}"  
      schema: "{{ env_var('ANALYTICS_DB_SCHEMA_NAME') }}" 
  target: analytics_postgres  