dbt_poc:
  outputs:
    analytics_postgres:
      type: postgres
      host: cow-analytics-db.cgabamo3x0wl.eu-central-1.rds.amazonaws.com
      port: 5432
      user: solver_slippage_readonly
      password: "{{ env_var('ANALYTICS_PASSWORD') }}"
      dbname: solver_slippage
      schema: aurelie
  target: analytics_postgres  